apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-susano
  namespace: susano-gestion-projet
  labels:
    app: app-gesprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-gesprod
  template:
    metadata:
      labels:
        app: app-gesprod
      namespace: susano-gestion-projet
    spec:
      containers:
      - name: app-susano
        image: susanoodev/app-gestionproduits:1.0.2
        env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mydbsecret
              key: USERNAME
        - name: DATABASE_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: mydbsecret
              key: HOSTNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mydbsecret
              key: PASSWORD