apiVersion: v1
kind: Service
metadata:
  labels:
    name: gesprod-svc
  name: gesprodservice
  namespace: susano-gestion-projet
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: app-gesprod