pipeline
{
    agent any
    stages
    {
        stage('Getting code from the github repo')
        {
            steps
            {
                git branch: 'delivery',
                credentialsId: 'c427e054-e135-4acb-9ce1-0d3353f37afb',
                url: 'https://github.com/SusanooDev/Susanoo.git'
            }
        }

        stage('Deployment with k8s')
        {
            steps
            {
                slackSend (channel: 'devops' ,message: 'lancement du déploiment de app-gestionproduits avec k8s ...')
                dir("k8s-manifests"){
                    sh "kubectl create -f gesprod-namespace.yaml"
                    sh "kubectl create -f gesprod-deploy.yaml"
                    sh "kubectl create -f gesprod-service.yaml"
                    sh "kubectl create -f mysql-pod.yaml"
                    sh "kubectl create -f mysql-service.yaml"
                    sh "kubectl create -f phpmyadmin-pod.yaml"
                    sh "kubectl create -f phpmyadmin-service.yaml"
                }
            }
        }
    }
}