apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod
  namespace: susano-gestion-projet
  labels:
    app: bd-mysql

spec:
  containers:
  - name: mysqlpod
    image: mysql:8.0.32 --> mon image
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mydbsecret
            key: ROOTPASSWORD
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mydbsecret
            key: PASSWORD
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: mydbsecret
            key: USERNAME
  restartPolicy: Never