apiVersion: v1
kind: Service
metadata:
  labels:
    name: mysql-svc
  name: mysqlservice
  namespace: susano-gestion-projet
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: bd-mysql