apiVersion: v1
kind: Pod
metadata:
  name: pmapod
  namespace: susano-gestion-projet
  labels:
    app: pma

spec:
  containers:
  - name: pmapod
    image: phpmyadmin/phpmyadmin
    env:
      - name: PMA_HOST
        valueFrom:
          secretKeyRef:
            name: mydbsecret
            key: HOSTNAME
  restartPolicy: Never